4_12_visiting screen
daniiliv/surf-flutter-course-ivanovd pull request #16
Opened 2022-08-28 20:12 UTC by daniiliv

![image](https://user-images.githubusercontent.com/36517601/187092730-89c4cea5-5888-4e75-ab36-2a230480b6d6.png)
![image](https://user-images.githubusercontent.com/36517601/187092738-0f764878-6786-4db4-8491-ba910d8364cb.png)

2022-08-28 20:16 UTC, daniiliv commented on lib/ui/screen/sight_card.dart
> +/// * [enableShareButton] - признак отображения кнопки "поделиться".
@GeorgeOblomov как думаешь, хорошо ли я сделал, что SightCart решил использовать ещё и для отображения информации о посещении в списке избранного?
По идее классно, что код переиспользуется, нет дублирования.

2022-08-28 20:17 UTC, daniiliv commented on lib/ui/screen/sight_card.dart
> +/// * [enableShareButton] - признак отображения кнопки "поделиться".
@GeorgeOblomov ещё прикол в том, что мне пришлось из SightCard вниз по дереву параметры передавать для отображения нужных кнопок в карточке. Например, "enableToFavouritesButton". Это, оказывается, так сложно, когда у тебя большая вложенность. На проектах это вообще насколько частая проблема и как решается?

2022-08-28 20:21 UTC, daniiliv commented on lib/ui/screen/components/custom_app_bar.dart
> +class CustomAppBar extends StatelessWidget implements PreferredSizeWidget {
@GeorgeOblomov ещё я решил вынести AppBar как общий компонент и переиспользовать в дальнейшем. 
Посмотри, пожалуйста, правильно ли я сделал? Мб, нужно было не заморачиваться с PreferredSizeWidget и сделать обычный материал AppBar?

2022-08-29 17:08 UTC, GeorgeOblomov commented on lib/ui/screen/components/custom_app_bar.dart
> +class CustomAppBar extends StatelessWidget implements PreferredSizeWidget {
Да! Здорово придумал. Очень полезно так делать!

2022-08-29 17:08 UTC, GeorgeOblomov commented on lib/ui/screen/components/custom_app_bar.dart
> +      child: Container(
Единственное, что Container здесь лучше просто на Padding заменить, раз ничего из Container нам ничего не нужно.

2022-08-29 17:13 UTC, GeorgeOblomov commented on lib/ui/screen/components/custom_bottom_navigation_bar.dart
> +            icon: Icon(Icons.event_note),
Иконочки с фигмы лучше загрузить.

2022-08-29 17:20 UTC, GeorgeOblomov commented on lib/ui/screen/sight_card.dart
> +/// * [enableShareButton] - признак отображения кнопки "поделиться".
Точно сделал правильно! А вот как сделать лучше, тут уже от навыков программиста зависит)) Точных рекомендаций тебе дать не могу, решений огромное множество. Мне лично нравится идея, сделать базовый класс карточки например BaseSightCard в котором будет реализован общий дизайн, а вот например список иконок отобржаемых карточкой или текст сделать отдельными абстрактными полями и использовать в самом виджете, далее сделать нужных наследников например FavoriteSightCard и в нем уже переопределить абстрактные поля. И тогда тебе только остается использовать конкретные реализации зависимости от места использования. Очень удобно как по мне))

2022-08-29 17:26 UTC, GeorgeOblomov commented on lib/ui/screen/visiting_screen.dart
> +    return mocks
Лучше сразу посещенные места передавать через конструктор.

2022-08-29 17:31 UTC, GeorgeOblomov requested changes
Все здорово! Я так по мелочам отписал. Поправь чуток. Если что стучи в телегу.

2022-08-29 20:49 UTC, daniiliv commented on lib/ui/screen/components/custom_bottom_navigation_bar.dart
> +            icon: Icon(Icons.event_note),
> Иконочки с фигмы лучше загрузить. Это не супер обязательно, но будем стараться соответствовать дизайну.

Как SVG в ассеты загружать, получается?

2022-08-29 20:54 UTC, daniiliv commented on lib/ui/screen/visiting_screen.dart
> +    return mocks
> Лучше сразу места передавать через конструктор. А ты один раз тут только используешь _VisitingList? Пытаюсь понять зачем тогда bool visited.

Тут, получается, _VisitingList отображает список "Посетил", если visited = true, иначе показывает список "Хочу посетить". В 118 строчке раскрывается задумка этого свойства "visited":
(element) => visited ? element.visited : !element.visited,

То есть так отбор делается по этому признаку. Не знаю, мб как-то можно более читабельнее сделать. Буду благодарен, если подскажешь)

2022-08-29 20:57 UTC, daniiliv commented on lib/ui/screen/sight_card.dart
> +/// * [enableShareButton] - признак отображения кнопки "поделиться".
> Точно сделал правильно! А вот как сделать лучше, тут уже от навыков программиста зависит)) Точных рекомендаций тебе дать не могу, решений огромное множество. Мне лично нравится идея, сделать базовый класс карточки например BaseSightCard в котором будет реализован общий дизайн, а вот например список иконок отобржаемых карточкой или текст сделать отдельными абстрактными полями и использовать в самом виджете, далее сделать нужных наследников например FavoriteSightCard и в нем уже переопределить абстрактные поля. И тогда тебе только остается использовать конкретные реализации в зависимости от места использования. И тогда прокидывать ничего не придется. Очень удобно как по мне))

А есть какой-то простой пример наследования в контексте виджетов? Пока в голове не могу уложить, как делать свои виджеты с использованием наследования)

2022-08-30 07:03 UTC, GeorgeOblomov commented on lib/ui/screen/sight_card.dart
> +/// * [enableShareButton] - признак отображения кнопки "поделиться".
Я имел в виду, что то подобное
```dart
abstract class BaseClass extends StatelessWidget {
  abstract List<String> assets;
  
  @override 
  Widget build(BuildContext context) {
    return Column(
      children: assets.map((asset) {
        return Image.asset(asset);
      });
    );
  }
}

class OneAssetWidget extends BaseClass {
  @override
  List<String> assets = ['assets/icons/heart.png'];
}

class TwoAssetsWidget extends BaseClass {
  @override
  List<String> assets = ['assets/icons/heart.png', 'assets/icons/exit.png'];
}
```

2022-08-30 07:03 UTC, GeorgeOblomov commented on lib/ui/screen/components/custom_bottom_navigation_bar.dart
> +            icon: Icon(Icons.event_note),
А ты выгружай png.

2022-08-31 12:58 UTC, daniiliv commented
@GeorgeOblomov попробовал сделать виджеты через наследование. Посмотри, насколько стало читабельнее. Можно ли что-то улучшить ещё?

2022-08-31 13:02 UTC, daniiliv commented on lib/ui/screen/visiting_screen.dart
> +                  .map((sight) => showVisitedSights
Можно ли как-то не подвязываться здесь к условию showVisitedSights? 
Типа как в строке 127 я просто подставляю виджет для отображения пустого списка мест. Хочется тоже самое с карточками сделать. Но не получается, т.к. надо модель sight передавать в конструктор.

2022-08-31 14:56 UTC, daniiliv commented on lib/ui/screen/visiting_screen.dart
> +                  .map((sight) => showVisitedSights
Ещё вопрос... а если у нас появится третья вкладка, обычным bool уже не обойтись, то есть мой код в данном случае слаборасширяемый. Как бы ты сделал?

2022-08-31 15:46 UTC, GeorgeOblomov commented
Как по мне, хорошо сделал. Посмотри по комментам и избавься от bool. Ставлю апрув, чтоб мог двигаться дальше.

2022-08-31 15:46 UTC, GeorgeOblomov approved these changes

2022-08-31 16:21 UTC, merged